name: Frontend Deploy

on:
  push:
    paths:
      - 'front-end/**'
    branches:
      - main
    tags:
      - 'frontend-v*'

env:
  PROJECT_PATH: front-end
  SERVICE_NAME: streamhub-frontend
  AWS_REGION: us-east-1

jobs:
  deploy-dev:
    name: Deploy to Development (LocalStack)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.PROJECT_PATH }}/package-lock.json

      - name: Install dependencies
        run: cd ${{ env.PROJECT_PATH }} && npm ci

      - name: Build application
        run: cd ${{ env.PROJECT_PATH }} && npm run build

      - name: Setup LocalStack
        run: |
          docker run -d \
            --name localstack-frontend \
            -p 4567:4566 \
            -e SERVICES=s3,cloudfront \
            -e DEBUG=1 \
            localstack/localstack:3.0

      - name: Wait for LocalStack
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:4567/_localstack/health; do sleep 2; done'

      - name: Setup AWS CLI for LocalStack
        run: |
          pip install awscli-local
          export AWS_ACCESS_KEY_ID=test
          export AWS_SECRET_ACCESS_KEY=test
          export AWS_DEFAULT_REGION=us-east-1

      - name: Create S3 bucket for frontend
        run: |
          awslocal s3 mb s3://${{ env.SERVICE_NAME }} --endpoint-url http://localhost:4567

      - name: Upload frontend to S3
        run: |
          cd ${{ env.PROJECT_PATH }}
          awslocal s3 sync dist/ s3://${{ env.SERVICE_NAME }}/ \
            --endpoint-url http://localhost:4567 \
            --delete

      - name: Configure S3 for static website hosting
        run: |
          awslocal s3 website s3://${{ env.SERVICE_NAME }} \
            --index-document index.html \
            --error-document error.html \
            --endpoint-url http://localhost:4567

      - name: Test frontend deployment
        run: |
          echo "Frontend deployed to LocalStack S3"
          echo "Access at: http://localhost:4567/${{ env.SERVICE_NAME }}"

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/frontend-v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.PROJECT_PATH }}/package-lock.json

      - name: Install dependencies
        run: cd ${{ env.PROJECT_PATH }} && npm ci

      - name: Build application
        run: cd ${{ env.PROJECT_PATH }} && npm run build

      - name: Deploy to production
        run: |
          echo "Production deployment would go here"
          echo "Tag: ${{ github.ref_name }}"