name: Package

on:
  workflow_call:

jobs:
  Package:
    runs-on: [arc-runner-medium]
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          
      - name: Install Dependencies
        shell: bash
        run: npm ci --ignore-scripts

      - name: Cache dependencies
        uses: actions/cache@v4
        env:
          cache-name: node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Build package
        run: npm run build

      - name: Uploading final package
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
