name: Prod

on:
  push:
    tags:
      - "*"

jobs:
  Prepare:
    uses: ./.github/workflows/dependencies.yml

  Run:
    needs: Prepare
    uses: ./.github/workflows/lint-test.yml

  Build:
    needs: Run
    uses: ./.github/workflows/package.yml


  Prod:
    needs: [Build, Prepare, Run]
    uses: ./.github/workflows/deploy.yml
    with:
      AWS_ACCOUNT_ID: 00000000000
      AWS_REGION: us-east-1
      ENVIRONMENT_NAME: prod
      GIT_ENVIRONMENT: prod
    secrets: inherit
